#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7A1C87E3F5BC42A8 (davidism@gmail.com)
#
Name     : Werkzeug
Version  : 0.15.4
Release  : 67
URL      : https://files.pythonhosted.org/packages/59/2d/b24bab64b409e22f026fee6705b035cb0698399a7b69449c49442b30af47/Werkzeug-0.15.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/2d/b24bab64b409e22f026fee6705b035cb0698399a7b69449c49442b30af47/Werkzeug-0.15.4.tar.gz
Source99 : https://files.pythonhosted.org/packages/59/2d/b24bab64b409e22f026fee6705b035cb0698399a7b69449c49442b30af47/Werkzeug-0.15.4.tar.gz.asc
Summary  : The comprehensive WSGI web application library.
Group    : Development/Tools
License  : BSD-3-Clause OFL-1.1
Requires: Werkzeug-license = %{version}-%{release}
Requires: Werkzeug-python = %{version}-%{release}
Requires: Werkzeug-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools-legacypython
BuildRequires : tox
BuildRequires : virtualenv

%description
Requirements :
- werkzeug : http://werkzeug.pocoo.org
- jinja : http://jinja.pocoo.org
- couchdb 0.72 & above : https://couchdb.apache.org/
- couchdb-python 0.3 & above : https://github.com/djc/couchdb-python

%package license
Summary: license components for the Werkzeug package.
Group: Default

%description license
license components for the Werkzeug package.


%package python
Summary: python components for the Werkzeug package.
Group: Default
Requires: Werkzeug-python3 = %{version}-%{release}
Provides: werkzeug-python

%description python
python components for the Werkzeug package.


%package python3
Summary: python3 components for the Werkzeug package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Werkzeug package.


%prep
%setup -q -n Werkzeug-0.15.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557935827
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Werkzeug
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/Werkzeug/LICENSE.rst
cp src/werkzeug/debug/shared/FONT_LICENSE %{buildroot}/usr/share/package-licenses/Werkzeug/src_werkzeug_debug_shared_FONT_LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Werkzeug/LICENSE.rst
/usr/share/package-licenses/Werkzeug/src_werkzeug_debug_shared_FONT_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
